insert offices
Gabrielnero000/FindOffice-Server pull request #8
Opened 2020-11-14 21:50 UTC by florencerc

2020-11-14 22:17 UTC, Gabrielnero000 requested changes

2020-11-14 22:17 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +    def addOffices(self, id_owner, address, district, number, extra, scoring, nScore):
O parâmetro vai ser um dicionário com todos esses valores como chaves.

2020-11-14 22:17 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        sql = "INSERT INTO offices (ownerId, address, district, number, extra, scoring, nScore) VALUES (%s, %s, %s, %s, %s, %s, %s)"
O ID não é parte do insert, ele só vai existir depois de inserido

2020-11-14 22:17 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +    def addOffices(self, id_owner, address, district, number, extra, scoring, nScore):
A função é addOffice, no singular

2020-11-14 22:17 UTC, Gabrielnero000 commented on backend/tenant/test_tenant.py
> +def testAddOffices():
O teste não é o que deveria ser. Olha aqui: https://github.com/Gabrielnero000/FindOffice-Server/blob/69e2a0cbfc737e50d4b6bac82ec3107d0202bd7b/backend/auth/test_auth.py#L14

2020-11-16 15:52 UTC, florencerc commented on backend/tenant/tenant.py
> +        sql = "INSERT INTO offices (ownerId, address, district, number, extra, scoring, nScore) VALUES (%s, %s, %s, %s, %s, %s, %s)"
mas a tabela office tem dois IDs, o do office e o do owner né? nenhum dos dois vai ser inserido? eu achei que só o officeID é que não precisava ser inserido

2020-11-16 22:22 UTC, Gabrielnero000 approved these changes

2020-11-16 22:22 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        sql = "INSERT INTO offices (ownerId, address, district, number, extra, scoring, nScore) VALUES (%s, %s, %s, %s, %s, %s, %s)"
Ah, verdade kkkk. Tá certo, é isso mesmo, o `ownerId` é parâmetro.

2020-11-16 22:23 UTC, Gabrielnero000 requested changes

2020-11-16 22:23 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        values = (offices['id_owner'], offices['address'], offices['district'],
Aqui você usa `offices` mas o parâmetro é `office`. Coloca tudo pra `office`.

2020-11-17 20:41 UTC, Gabrielnero000 requested changes

2020-11-17 20:41 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +                  offices['number'], offices['extra'], offices['scoring'], offices['nScore'])
Essa rota vai ser usada pelo locatário, então ele não pode modificar `scoring` e `nScore`, esses parâmetros não devem fazer parte da operação e devem ser inicializados com zero.

2020-11-25 22:43 UTC, Gabrielnero000 requested changes

2020-11-25 22:43 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        values = (office['id_owner'], office['address'], office['district'],
No caso, a inicialização com zero seria aqui. Seria:
`values = (office['id_owner'], office['address'], office['district'], office['number'], office['extra'], 0, 0])`

2020-11-25 22:43 UTC, Gabrielnero000 commented on backend/tenant/test_tenant.py
> +        'scoring': 0,
`scoring` e `nScore` não vão fazer parte do dicionário.

2020-11-25 22:44 UTC, Gabrielnero000 requested changes

2020-11-25 22:44 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        db_office = cursor.fetchone()
Checa se o `db_office` não é `None`. Se for, deu erro ao inserir.

2020-11-28 21:34 UTC, Gabrielnero000 requested changes

2020-11-28 21:34 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        if db_office is None
Corrigir indentação.

2020-11-28 21:34 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        values = (office['id_owner'], office['address'], office['district'],
Modificar para dar suporte a duas outras propriedades: `daily_rate` que é float e `type` que é string. Propagar essas modificações para a tabela.

2020-11-30 22:49 UTC, Gabrielnero000 requested changes

2020-11-30 22:49 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        values = (office['id_owner'], office['address'], office['district'],
Atualizar para as novas tabelas

2020-11-30 22:49 UTC, Gabrielnero000 commented on backend/tenant/test_tenant.py
> +<<<<<<< HEAD
Isso aqui ficou de algum conflito que você não resolveu. Dá uma olhada.

2020-12-01 00:27 UTC, Gabrielnero000 requested changes

2020-12-01 00:27 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        values = (office['id_owner'], office['address'], office['district'],
Remover daqui, agora é parte do `landmaster`

2020-12-01 00:27 UTC, Gabrielnero000 commented on backend/tenant/test_tenant.py
> +>>>>>>> main
Resquício de merge.

2020-12-01 00:27 UTC, Gabrielnero000 commented on .vscode/settings.json
> +<<<<<<< HEAD
Resquício de merge

2020-12-01 01:12 UTC, Gabrielnero000 approved these changes

2020-12-01 01:13 UTC, merged