Feature/modify office
Gabrielnero000/FindOffice-Server pull request #9
Opened 2020-11-15 18:45 UTC by tuliosouza99

2020-11-16 22:21 UTC, Gabrielnero000 requested changes

2020-11-16 22:21 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        db_office = cursor.fetchone()
No SQL o UPDATE só não retorna nada, então o `fetchone()` vai ser sempre `None`. O que tu pode fazer é adicionar um RETURNING (https://stackoverflow.com/a/38948920) e verificar se o dict retornado é diferente do que o recebido.

2020-11-17 11:22 UTC, tuliosouza99 commented on backend/tenant/tenant.py
> +        db_office = cursor.fetchone()
Atualizei nesse commit (https://github.com/Gabrielnero000/FindOffice-Server/pull/9/commits/b3c7ce9ab5c231e334366ff46cd4f7bbb7f5f2fc) aqui.

2020-11-19 20:00 UTC, Gabrielnero000 approved these changes

2020-11-19 20:00 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +        if db_office != tuple(office_info.values()):
O cursor tá configurado pra retornar um dict, dá pra compara direto com o office_info. No caso, a operação falhou se o db_office e o office_info são iguais (significa que não conseguiu modificar).

2020-11-19 20:00 UTC, Gabrielnero000 commented on backend/tenant/tenant.py
> +            f"scoring = '{office_info['scoring']}', "
Essa rota vai ser usada pelo locatário, então ele não pode modificar `scoring` e `nScore`, esses parâmetros não devem fazer parte da operação.

2020-11-19 20:00 UTC, merged